from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path("", views.login, name="login"),
    path("logincontroller/", views.logincontroller, name="logincontroller"),
    path("logout/", views.logout, name="logout"),
    path("dashboard/", views.home, name="home"),
    path("AAA/", views.aaa, name="AAA"),
    path("aaacontroller/", views.aaacontroller, name="aaacontroller"),
    path("ddos/", views.ddos, name="DDOS"),
    path("ntp/", views.ntp, name="ntp"),
    path("log/", views.log, name="Log"),
    path("CREATEUSER/", views.Createuser, name="CREATE_USER"),
    path("deleteuser/", views.deleteuser, name="DELETE_USER"),
    path("showusers/", views.users, name="showusers"),
    path("createuserform/", views.createuserform, name="createuserform"),
    path("deleteuser/<int:id>", views.deleteuser, name="deleteuser"),
    path("log/", views.log, name="logmanagement"),
    path("date/", views.dateform, name="date"),
    path("deletelogs/", views.deletelogs, name="deletelogs"),
    path("deletelogconfirm/", views.deletelogconfirm, name="deletelogconfirm"),
    path(
        "deleteonosseclogconfirm/",
        views.deleteonosseclogconfirm,
        name="deleteonosseclogconfirm",
    ),
    path("deleteonosseclogs/", views.deleteonosseclogs, name="deleteonosseclogs"),
    path("securitystats/", views.securitystats, name="securitystats"),
    path("addconfig/", views.addconfig, name="configcontroller"),
    path("extraconfig/", views.addextraconfig, name="extraconfig"),
    path("addpassword/", views.addconfigpassword, name="addconfigpasswordcontroller"),
    path("modifypassword/", views.modifypassword, name="modifypassword"),
    path("disablepassword/", views.disablepassword, name="disablepassword"),
    path(
        "passwordisable/", views.disablepasswordconfirm, name="disablepasswordconfirm"
    ),
    path(
        "viewpasswordconfiguration/",
        views.viewpasswordconfiguration,
        name="viewconfigurationpassword",
    ),
    path("modifyhttp/", views.modifyhttp, name="modifyhttp"),
    path("disablehttp/", views.disablehttp, name="disablehttp"),
    path("viewhttp/", views.viewhttp, name="viewhttp"),
    path("configtls/", views.configtls, name="configtls"),
    path("modifytls/", views.modifytls, name="modifytls"),
    path("disabletls/", views.disabletls, name="disabletls"),
    path("viewtls/", views.viewtls, name="viewtls"),
    path("confighttp/", views.confighttp, name="confighttp"),
    path("addfire/", views.addfire, name="addfire"),
    path("addfirecontroller/", views.addfirecontroller, name="addfirecontroller"),
    path("viewrules/", views.viewrules, name="viewrules"),
    path("httpdisable/", views.disablehttpconfirm, name="httpdisableconfirm"),
    path("deleterules/<str:id>", views.deleterules, name="deleterules"),
    path("tlsdisable/", views.disabletlsconfirm, name="disabletlsconfirm"),
    path("onosseclog/", views.onosseclog, name="onosseclog"),
    path("onossecdateform/", views.onossecdateform, name="onossecdateform"),
    path("disablentp/", views.disablentp, name="disablentp"),
    path("configntp/", views.configntp, name="configntp"),
    path("addrulesbyport/", views.addrulesbyport, name="addrulesbyport"),
    path(
        "addrulesbyportcontroller/",
        views.addrulesbyportcontroller,
        name="addrulesbyportcontroller",
    ),
    path("viewradius/", views.viewradius, name="viewradius"),
    path("aaalogs/", views.aaalog, name="aaalog"),
    path("aaadate/", views.aaadateform, name="aaadate"),
    path("deleteaaalogconfirm/", views.deleteaaalogconfirm, name="deleteaaalogconfirm"),
    path("deleteaaalogs/", views.deleteaaalogs, name="deleteaaalogs"),
    path("addrulesbysrc/", views.addrulesbysrc, name="addrulesbysrc"),
    path(
        "addrulesbysrccontroller/",
        views.addrulesbysrccontroller,
        name="addrulesbysrccontroller",
    ),
]
