# Generated by Django 4.1.7 on 2023-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdntoolswitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=200),
        ),
    ]
