# Generated by Django 5.0.3 on 2024-04-10 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdntoolswitch', '0002_usermanagement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NtpConfigRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntpserver', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('output', models.TextField()),
                ('usercreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdntoolswitch.usermanagement')),
            ],
            options={
                'db_table': 'ntpconfigrecords',
            },
        ),
        migrations.CreateModel(
            name='OnosServerManagement',
            fields=[
                ('idonosservermanagement', models.BigAutoField(primary_key=True, serialize=False)),
                ('primaryip', models.CharField(max_length=200)),
                ('multipleconfigjson', models.TextField()),
                ('usercreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdntoolswitch.usermanagement')),
            ],
            options={
                'db_table': 'onosservermanagement',
            },
        ),
    ]
