# Generated by Django 5.0.3 on 2024-04-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdntoolswitch', '0004_alter_onosservermanagement_usercreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntpconfigrecords',
            name='usercreated',
            field=models.CharField(max_length=200),
        ),
    ]
