# Generated by Django 5.0.3 on 2024-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdntoolswitch', '0005_alter_ntpconfigrecords_usercreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('usercreated', models.CharField(max_length=200)),
                ('portConf', models.TextField()),
            ],
            options={
                'db_table': 'deviceconfigrecords',
            },
        ),
        migrations.RemoveField(
            model_name='onosservermanagement',
            name='primaryip',
        ),
        migrations.AddField(
            model_name='onosservermanagement',
            name='iplist',
            field=models.TextField(default=''),
        ),
    ]
